name: Build

# you probably want to restrict this in a separate workflow
on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-20.04
            cibw_archs: "native"
          - os: ubuntu-20.04
            cibw_archs: "aarch64"

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        if: matrix.cibw_archs == 'aarch64'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.1
        env:
          # configure cibuildwheel to build native and aarch64 archs
          CIBW_ARCHS: ${{ matrix.cibw_archs }}

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
